# Generated by Django 2.1.2 on 2018-11-21 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0006_auto_20181120_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 21, 22, 55, 36, 936803, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
