# Generated by Django 2.1.2 on 2018-11-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0007_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
