# Generated by Django 2.1.2 on 2018-12-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0008_auto_20181206_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='following_user',
        ),
    ]
