# Generated by Django 2.1.2 on 2018-12-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0009_auto_20181206_0030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('following_user', 'followed_user')},
        ),
    ]
